#!/bin/bash

BASEDIR=`dirname "$0"`

for f in ${BASEDIR}/../docbook/6.1/en/*.xml
do
    BASENAME=$(basename "$f" .xml)
    python ${BASEDIR}/DocBookToReST.py ${f} > ${BASEDIR}/../src/en/source/${BASENAME}.rst
done
